export const iconImagePath = "/images/privacy";
export const iconList = [
  { iconName: "001", iconPath: `${iconImagePath}/001.png`, description: "개인정보" },
  { iconName: "002", iconPath: `${iconImagePath}/002.png`, description: "개인영상정보" },
  { iconName: "003", iconPath: `${iconImagePath}/003.png`, description: "민감정보" },
  { iconName: "004", iconPath: `${iconImagePath}/004.png`, description: "생체정보" },
  { iconName: "005", iconPath: `${iconImagePath}/005.png`, description: "개인위치정보" },
  { iconName: "006", iconPath: `${iconImagePath}/006.png`, description: "고유식별정보" },
  { iconName: "007", iconPath: `${iconImagePath}/007.png`, description: "주민등록번호" },
  { iconName: "008", iconPath: `${iconImagePath}/008.png`, description: "여권번호" },
  { iconName: "009", iconPath: `${iconImagePath}/009.png`, description: "운전면허번호" },
  { iconName: "010", iconPath: `${iconImagePath}/010.png`, description: "외국인등록번호" },
  { iconName: "011", iconPath: `${iconImagePath}/011.png`, description: "처리항목" },
  { iconName: "012", iconPath: `${iconImagePath}/012.png`, description: "처리목적" },
  { iconName: "013", iconPath: `${iconImagePath}/013.png`, description: "추가적 이용" },
  { iconName: "014", iconPath: `${iconImagePath}/014.png`, description: "자동화 수집" },
  { iconName: "015", iconPath: `${iconImagePath}/015.png`, description: "행태정보 수집" },
  { iconName: "016", iconPath: `${iconImagePath}/016.png`, description: "가명정보 처리" },
  { iconName: "017", iconPath: `${iconImagePath}/017.png`, description: "국외이전" },
  { iconName: "018", iconPath: `${iconImagePath}/018.png`, description: "제3자 제공" },
  { iconName: "019", iconPath: `${iconImagePath}/019.png`, description: "처리위탁" },
  { iconName: "020", iconPath: `${iconImagePath}/020.png`, description: "보유기간(설정)" },
  { iconName: "022", iconPath: `${iconImagePath}/022.png`, description: "파기" },
  { iconName: "023", iconPath: `${iconImagePath}/023.png`, description: "정보주체의 권리의무" },
  { iconName: "024", iconPath: `${iconImagePath}/024.png`, description: "안전성확보조치" },
  { iconName: "025", iconPath: `${iconImagePath}/025.png`, description: "처리방침변경" },
  { iconName: "026", iconPath: `${iconImagePath}/026.png`, description: "개인정보보호인증" },
  { iconName: "027", iconPath: `${iconImagePath}/027.png`, description: "관리수준진단" },
  { iconName: "028", iconPath: `${iconImagePath}/028.png`, description: "법정대리인" },
  { iconName: "029", iconPath: `${iconImagePath}/029.png`, description: "개인정보보호책임자" },
  { iconName: "030", iconPath: `${iconImagePath}/030.png`, description: "국내대리인" },
  { iconName: "031", iconPath: `${iconImagePath}/031.png`, description: "고충처리부서" },
  { iconName: "032", iconPath: `${iconImagePath}/032.png`, description: "권익침해 구제" },
  { iconName: "033", iconPath: `${iconImagePath}/033.png`, description: "열람청구" },
  { iconName: "034", iconPath: `${iconImagePath}/034.png`, description: "영상정보처리기기" },
];
